web:
  build: .
  volumes:
    - .:/var/www/html
  ports:
    - "8000:80"
  links:
    - db
  environment:
    DB_HOST: db
db:
  image: mysql:5.6
  volumes:
    - /var/data/dockermysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: techblog
